version: 2.1


jobs:
  build-and-lint: 
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
              python3 -m venv venv
              . venv/bin/activate
              make install
              # Install hadolint
              wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
      - save_cache:
          paths: [./venv]
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      # run lint!
      - run:
          name: run lint
          command: |
              . venv/bin/activate
              make lint  

  run-docker: 
    docker:
      - image: ubuntu:18.04
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install docker
          command: |
               yum update -y
               amazon-linux-extras install docker
               service docker start
               ./run_docker.sh
      - run:
          name: build docker
          command: |
              ./run_docker.sh
  
  upload-docker-container: 
    docker:
      - image: amazon/aws-cli	
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: push docker conatainer
          command: |
              ./upload_docker.sh

              
workflows:
  default:
     jobs:
      - run-docker
